/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Cloud(props) {
  const { nodes, materials } = useGLTF("/models/cloud.glb");
  const cloud = useRef();

  useFrame((state, delta) => {
    cloud.current.position.x += delta;
  });

  return (
    <group ref={cloud} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry}>
        <meshStandardMaterial color="white" />
      </mesh>
      <mesh position={[-5, 0, 0]} geometry={nodes.Sphere001.geometry}>
        <meshStandardMaterial color="white" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/cloud.glb");
