/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Island(props) {
  const { nodes, materials } = useGLTF("/models/singleIsland.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Earth}
      />
      <mesh
        receiveShadow
        geometry={nodes.Cube001_1.geometry}
        material={materials.Grass}
      />
    </group>
  );
}

useGLTF.preload("/models/singleIsland.glb");
