/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Phone(props) {
  const { nodes, materials } = useGLTF("/models/phone.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Phone.geometry} rotation={[Math.PI / 2, 0, 0]}>
        <meshStandardMaterial color="grey" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/phone.glb");
