/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { MATERIALS } from "../state/Config.js";

export function IslandPoints({ showPoints, ...props }) {
  const { nodes } = useGLTF("./models/singleIsland.glb");
  const geom1 = nodes.Cube001_1.geometry;
  const geom2 = nodes.Cube001.geometry;

  return (
    <group {...props} dispose={null}>
      {showPoints ? (
        <group>
          <points args={[geom1]}>
            <pointsMaterial color="green" size={0.025} />
          </points>
          <points args={[geom2]}>
            <pointsMaterial color={0x210f00} size={0.025} />
          </points>
        </group>
      ) : (
        <group>
          <mesh geometry={nodes.Cube001.geometry} material={MATERIALS.EARTH} />
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={MATERIALS.GRASS}
          />
        </group>
      )}
    </group>
  );
}

useGLTF.preload("./models/singleIsland.glb");
