/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PumpkinIsland({ showPoints, ...props }) {
	const { nodes, materials } = useGLTF("./models/pumpkin.glb");
	const geom1 = nodes["Jack-o’-lantern_1_1"].geometry;
	const geom2 = nodes["Jack-o’-lantern_1_2"].geometry;
	const geom3 = nodes["Jack-o’-lantern_1_3"].geometry;

	return (
		<group scale={1.6} dispose={null}>
			{showPoints ? (
				<group>
					<points args={[geom1]}>
						<pointsMaterial color={0x210f00} size={0.025} />
					</points>
					<points args={[geom2]}>
						<pointsMaterial color={0x210f00} size={0.025} />
					</points>
					<points args={[geom3]}>
						<pointsMaterial color={0x210f00} size={0.025} />
					</points>
				</group>
			) : (
				<group>
					<mesh
						geometry={nodes["Jack-o’-lantern_1_1"].geometry}
						material={materials["Pumpkin Orange"]}
					/>
					<mesh
						geometry={nodes["Jack-o’-lantern_1_2"].geometry}
						material={materials["Pumpkin Orange Dark"]}
					/>
					<mesh
						geometry={nodes["Jack-o’-lantern_1_3"].geometry}
						material={materials["Pumpkin Stem"]}
					/>
				</group>
			)}
		</group>
	);
}

useGLTF.preload("./models/pumpkin.glb");
