/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: k. (https://sketchfab.com/k_nelms)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-mobile-phone-4ff99cf17b164e7b9790638c5d2ef4ce
Title: Low Poly Mobile Phone
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { SCENE } from "../state/Config";

export function AR({ fadeIn, fadeOut, ...props }) {
  const { nodes, materials } = useGLTF("./models/low_poly_mobile_phone.glb");
  const matRefs = {
    screen: useRef(),
    case: useRef(),
  };
  let fadeOutEnabled = fadeOut;
  let fadeInEnabled = fadeIn;

  useFrame((state, delta) => {
    if (fadeOutEnabled) {
      matRefs.screen.current.opacity -= delta * SCENE.FADE_DELAY;
      matRefs.case.current.opacity -= delta * SCENE.FADE_DELAY;
      if (matRefs.screen.current.opacity < 0) {
        matRefs.screen.current.opacity = 0;
        matRefs.case.current.opacity = 0;
      }
    }
    if (fadeInEnabled) {
      if (matRefs.screen.current.opacity >= 1) {
        matRefs.screen.current.opacity = 0;
        matRefs.case.current.opacity = 0;
      }
      matRefs.screen.current.opacity += delta * SCENE.FADE_DELAY;
      matRefs.case.current.opacity += delta * SCENE.FADE_DELAY;
      if (matRefs.screen.current.opacity >= 1) {
        matRefs.screen.current.opacity = 1;
        matRefs.case.current.opacity = 1;
        fadeInEnabled = false;
      }
    }
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 43.978, 0]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh geometry={nodes.Phone_Case_PhoneCase_Mat_0.geometry}>
              <meshLambertMaterial
                transparent={true}
                color={0x777777}
                ref={matRefs.case}
              />
            </mesh>
            <mesh geometry={nodes.Phone_Case_PhoneFace_Mat_0.geometry}>
              <meshLambertMaterial
                transparent={true}
                color={0x000000}
                ref={matRefs.screen}
              />
            </mesh>
          </group>
          {/* <mesh
						geometry={nodes.Phone_Camera_PhoneCase_Mat_0.geometry}
						position={[8.421, 57.722, -17.875]}
						rotation={[Math.PI / 4, 0, 0]}
						scale={[0.889, 1, 1]}
					>
						<meshLambertMaterial transparent={true} color={0x000000} />
					</mesh> */}
          <mesh
            geometry={nodes.Power_Button_PhoneButton_Mat_0.geometry}
            position={[15.24, 54.694, -10.453]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={[1, 1, 1.24]}
          >
            <meshLambertMaterial transparent={true} color={0xcc7306} />
          </mesh>
          <mesh
            geometry={nodes.Volume_Up_PhoneButton_Mat_0.geometry}
            position={[-15.122, 54.492, -10.657]}
            rotation={[0.787, 0, -3.053]}
            scale={[1, 1, 0.793]}
          >
            <meshLambertMaterial transparent={true} color={0xcc7306} />
          </mesh>
          <mesh
            geometry={nodes.Volume_Down_PhoneButton_Mat_0.geometry}
            position={[-15.121, 51.118, -7.296]}
            rotation={[0.787, 0, -3.053]}
            scale={[1, 1, 0.793]}
          >
            <meshLambertMaterial transparent={true} color={0xcc7306} />
          </mesh>
          <mesh
            geometry={nodes.Camera_1_PhoneFace_Mat_0.geometry}
            position={[9.743, 58.839, -20.064]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={1.696}
          >
            <meshLambertMaterial transparent={true} color={0xcc7306} />
          </mesh>
          <mesh
            geometry={nodes.Camera_2_PhoneFace_Mat_0.geometry}
            position={[9.743, 55.578, -16.803]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={1.696}
          >
            <meshLambertMaterial transparent={true} color={0xcc7306} />
          </mesh>
          <mesh
            geometry={nodes.Camera_Light_Camera_Light1_0.geometry}
            position={[6.831, 57.23, -18.455]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={0.875}
          >
            <meshLambertMaterial transparent={true} color={0xffffff} />
          </mesh>
          <mesh
            geometry={nodes.Camera_Front_PhoneButton_Mat_0.geometry}
            position={[-0.421, 66.193, -18.692]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={0.575}
          >
            <meshLambertMaterial transparent={true} color={0xcc7306} />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/low_poly_mobile_phone.glb");
