/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { SCENE } from "../state/Config";

export function Brush({ fadeIn, fadeOut, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/brush.gltf");
  for (const mat in materials) {
    materials[mat].transparent = true;
  }
  const matRefs = {
    part1: useRef(),
    part2: useRef(),
    part3: useRef(),
    part4: useRef(),
  };
  let fadeOutEnabled = fadeOut;
  let fadeInEnabled = fadeIn;

  useFrame((state, delta) => {
    if (fadeOutEnabled) {
      for (const part in matRefs) {
        matRefs[part].current.material.opacity -= delta * SCENE.FADE_DELAY;
      }
      if (matRefs.part1.current.material.opacity < 0) {
        for (const part in matRefs) {
          matRefs[part].current.material.opacity = 0;
        }
        fadeOutEnabled = false;
      }
    }
    if (fadeInEnabled) {
      if (matRefs.part1.current.material.opacity >= 1) {
        for (const part in matRefs) {
          matRefs[part].current.material.opacity = 0;
        }
      }
      for (const part in matRefs) {
        matRefs[part].current.material.opacity += delta * SCENE.FADE_DELAY;
      }
      if (matRefs.part1.current.material.opacity >= 1) {
        for (const part in matRefs) {
          matRefs[part].current.material.opacity = 1;
        }
        fadeInEnabled = false;
      }
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.3}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Mesh_1.geometry}
            material={materials["795548"]}
            ref={matRefs.part1}
          />
          <mesh
            geometry={nodes.Mesh_2.geometry}
            material={materials["455A64"]}
            ref={matRefs.part2}
          />
          <mesh
            geometry={nodes.Mesh_3.geometry}
            material={materials["039BE5"]}
            ref={matRefs.part3}
          />
          <mesh
            geometry={nodes.Mesh_0.geometry}
            material={materials["80DEEA"]}
            ref={matRefs.part4}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/brush.gltf");
