/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function DataViz(props) {
  const { nodes, materials } = useGLTF("./models/dataViz.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        position={[0, 2, 1.25]}
        scale={[1, 2, 1]}>
        <meshLambertMaterial color="grey" />
      </mesh>
      <mesh
        geometry={nodes.Cube.geometry}
        position={[0, 2.5, -1.25]}
        scale={[1, 2.5, 1]}>
        <meshLambertMaterial color="grey" />
      </mesh>
      <mesh
        geometry={nodes.Cube.geometry}
        position={[0, 3, -3.75]}
        scale={[1, 3, 1]}>
        <meshLambertMaterial color="orange" />
      </mesh>
      <mesh
        geometry={nodes.Cube.geometry}
        position={[0, 3.5, -6.25]}
        scale={[1, 3.5, 1]}>
        <meshLambertMaterial color="grey" />
      </mesh>
      <mesh
        geometry={nodes.Cube.geometry}
        position={[0, 1.5, 3.75]}
        scale={[1, 1.5, 1]}>
        <meshLambertMaterial color="grey" />
      </mesh>
      <mesh geometry={nodes.Cube.geometry} position={[0, 1, 6.25]}>
        <meshLambertMaterial color="grey" />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/dataViz.glb");
