/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dog(props) {
  const { nodes, materials } = useGLTF("./models/dog.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh001.geometry} material={materials.eyes} />
      <mesh
        geometry={nodes.Mesh001_1.geometry}
        material={materials.eyes_pupile}
      />
      <mesh geometry={nodes.nose.geometry} material={materials.nose} />
      <mesh
        geometry={nodes.Mesh002.geometry}
        material={materials["body_orange-light"]}
      />
      <mesh geometry={nodes.Mesh002_1.geometry}>
        <meshStandardMaterial color="darkorange" />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/dog.gltf");
