/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MATERIALS } from "../state/Config.js";

export function DRT(props) {
  const { nodes, materials } = useGLTF("./models/DRT-Text.gltf");
  console.log("Mats = ", materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.DRT001.geometry}
        material={MATERIALS.SHINY_ORANGE}
        position={[-1.09, -0.44, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/DRT-Text.gltf");
