/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Fish(props) {
  const { nodes, materials } = useGLTF("./models/fish.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_fish.geometry}
        material={materials.pink}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_fish_1.geometry}
        material={materials.greyLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_fish_2.geometry}
        material={materials._defaultMat}
      />
    </group>
  );
}

useGLTF.preload("./models/fish.gltf");
