/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Flag(props) {
  const { nodes, materials } = useGLTF("/models/flag.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube1351.geometry}
          material={materials["Blue.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube1351_1.geometry}
          material={materials["Brown.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube1351_2.geometry}
          material={materials["Metal.019"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/flag.gltf");
