/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Foundation(props) {
  const { nodes, materials } = useGLTF("./models/foundation.gltf");
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.formation_rock_1.geometry}>
          <meshStandardMaterial color={0x7a7676} />
        </mesh>
        <mesh
          geometry={nodes.formation_rock_2.geometry}
          material={materials.sand}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/foundation.gltf");
