/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export function Henge(props) {
  const { nodes, materials } = useGLTF("./models/henge.gltf");
  const stone = 0x777777;

  return (
    <group scale={0.25} position={[-2, 0.25, -3]} {...props} dispose={null}>
      <mesh geometry={nodes.dolmen1010.geometry}>
        <meshStandardMaterial color={stone} />
      </mesh>
      <mesh geometry={nodes.dolmen1011.geometry}>
        <meshStandardMaterial color={stone} />
      </mesh>
      <mesh geometry={nodes.dolmen1019.geometry}>
        <meshStandardMaterial color={stone} />
      </mesh>
      <mesh geometry={nodes.dolmen1020.geometry}>
        <meshStandardMaterial color={stone} />
      </mesh>
      <mesh position={[-7, 1, -8]} geometry={nodes.dolmen2001.geometry}>
        <meshStandardMaterial color={stone} />
      </mesh>
      <mesh geometry={nodes.dolmen2005.geometry}>
        <meshStandardMaterial color={stone} />
      </mesh>
      <mesh geometry={nodes.dolmen4008.geometry}>
        <meshStandardMaterial color={stone} />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/henge.gltf");
