/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export function Keyboard(props) {
  const { nodes, materials } = useGLTF("/models/keyboard.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube027.geometry}>
        <meshStandardMaterial color="grey" />
      </mesh>
      <mesh geometry={nodes.KEYs.geometry}>
        <meshStandardMaterial color="orange" />
      </mesh>
      <mesh geometry={nodes.Cube027_2.geometry}>
        <meshStandardMaterial color="grey" />
      </mesh>
      <mesh geometry={nodes.Cube027_4.geometry}>
        <meshStandardMaterial color="grey" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/keyboard.glb");
