/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Lamp(props) {
  const { nodes, materials } = useGLTF("./models/lampPost.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder096.geometry}
        material={materials["Black.012"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder096_1.geometry}
        material={materials["Yellow.007"]}
      />
    </group>
  );
}

useGLTF.preload("./models/lampPost.gltf");
