/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KurtSteiner (https://sketchfab.com/KurtSteiner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/filing-box-53d37f066180402ea4839dc3249e1f50
Title: Filing Box
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Project(props) {
  const { nodes, materials } = useGLTF("./models/filing_box.glb");
  return (
    <group {...props} dispose={null} scale={0.01}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/filing_box.glb");
