/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KurtSteiner (https://sketchfab.com/KurtSteiner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/filing-box-53d37f066180402ea4839dc3249e1f50
Title: Filing Box
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { SCENE } from "../state/Config";

export function Project({ fadeIn, fadeOut, direction, ...props }) {
  const { nodes, materials } = useGLTF("./models/filing_box.glb");
  const matRef = useRef();
  const groupRef = useRef();
  let fadeOutEnabled = fadeOut;
  let fadeInEnabled = fadeIn;

  useFrame((_, delta) => {
    if (fadeOutEnabled) {
      matRef.current.material.opacity -= delta * SCENE.FADE_DELAY;
      groupRef.current.position.x += delta * direction;
      if (matRef.current.material.opacity < 0) {
        matRef.current.opacity = 0;
        fadeOutEnabled = false;
      }
    }
    if (fadeInEnabled) {
      if (matRef.current.material.opacity >= 1) {
        matRef.current.material.opacity = 0;
      }
      matRef.current.material.opacity += delta * SCENE.FADE_DELAY;
      if (matRef.current.material.opacity >= 1) {
        matRef.current.material.opacity = 1;
        fadeInEnabled = false;
      }
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null} scale={0.01}>
      <mesh
        ref={matRef}
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/filing_box.glb");
