/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Rock(props) {
  const { nodes, materials } = useGLTF("/models/rock.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.menhir_moyen.geometry}>
        <meshStandardMaterial color={0xd1711d} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/rock.gltf");
