/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { SCENE } from "../state/Config";

export function SpaceShip({ fadeIn, fadeOut, direction, ...props }) {
  const { nodes, materials } = useGLTF("./models/spaceShip.gltf");
  const groupRef = useRef();
  const matRef = useRef();
  let fadeOutEnabled = fadeOut;
  let fadeInEnabled = fadeIn;

  useFrame((_, delta) => {
    if (fadeOutEnabled) {
      matRef.current.material.opacity -= delta * SCENE.FADE_DELAY;
      groupRef.current.position.x += delta * direction;
      if (matRef.current.material.opacity < 0) {
        matRef.current.material.opacity = 0;
        fadeOutEnabled = false;
      }
    }
    if (fadeInEnabled) {
      if (matRef.current.material.opacity >= 1) {
        matRef.current.material.opacity = 0;
      }
      matRef.current.material.opacity += delta * SCENE.FADE_DELAY;
      if (matRef.current.material.opacity >= 1) {
        matRef.current.material.opacity = 1;
        fadeInEnabled = false;
      }
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        ref={matRef}
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_1.geometry}
        material={materials.Mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_2.geometry}
        material={materials.Mat2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_3.geometry}
        material={materials.Window_Frame}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_4.geometry}
        material={materials.Mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_5.geometry}
        material={materials.Mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_6.geometry}
        material={materials.Window}
      />
    </group>
  );
}

useGLTF.preload("./models/spaceShip.gltf");
