/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function Tablet(props) {
  const { nodes, materials } = useGLTF("/models/tablet.glb");
  const texture = useTexture(props.map);
  texture.flipY = false;

  return (
    <group {...props} dispose={null}>
      <group scale={[0.1, 1.2, 0.9]}>
        <mesh geometry={nodes.Cube001.geometry}>
          <meshStandardMaterial color="#333333" />
        </mesh>
        <mesh geometry={nodes.Cube001_1.geometry}>
          <meshStandardMaterial map={texture} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/tablet.glb");
