/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tablet(props) {
  const { nodes, materials } = useGLTF("/models/tablet.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={[0.1, 1.2, 0.9]} rotation={[Math.PI, 0, -Math.PI / 8]}>
        <mesh geometry={nodes.Cube001.geometry}>
          <meshStandardMaterial color="#333333" />
        </mesh>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Tex} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/tablet.glb");
