/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export function TreePoints({ showPoints, ...props }) {
	const alphaRef = useRef(1);
	const triggerRef = useRef(false);

	const { nodes, materials } = useGLTF("./models/tree.gltf");
	const geom = nodes["tree-spruce"].geometry;

	useFrame((state, delta) => {
		if (showPoints) {
			alphaRef.current.opacity -= delta * 0.5;
			if (alphaRef.current.opacity < 0) {
				alphaRef.current.opacity = 0;
			}
		}
	});

	return (
		<group {...props} dispose={null}>
			{showPoints ? (
				<points args={[geom]}>
					<pointsMaterial
						ref={alphaRef}
						transparent={true}
						color="green"
						size={0.025}
					/>
				</points>
			) : (
				<mesh geometry={geom} material={materials.color_main} />
			)}
		</group>
	);
}

useGLTF.preload("./models/tree.gltf");
